# Generated by Django 3.0.8 on 2020-07-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_item_slider_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Sale', 'Sale'), ('New', 'New')], max_length=100),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=100)),
                ('upper_part', models.CharField(max_length=300)),
                ('middle_part', models.CharField(max_length=300)),
                ('lower_part', models.CharField(blank=True, max_length=200)),
                ('cross_part', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
    ]
