# Generated by Django 3.0.8 on 2020-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200721_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='front',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
    ]
