# Generated by Django 3.0.8 on 2020-07-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
